### ISSUE TITLE
Metrics の value が INT型のときに値が取れない

### ISSUE THREAD

**Issue by mida-hub** [syou6162/cloud_monitoring_metrics_fetch#2]
# 概要
Metrics の value が INT型のときに値が取れないようです
（value 項目にすべて 0 がセットされる）

README に記載の Usage だと値が取れます

恐らくここで値を取るときに

https://github.com/syou6162/cloud_monitoring_metrics_fetch/blob/b4f02fdf5e2917c070b5b87b572bf7c5cf92e4c7/main.go#L82

Double 型の値があれば拾えるけど、 INT 型の値の場合は
value が取得できず 0 になっているように見えます

# 実行コマンド
my-project は該当のプロジェクトに置き換えています

```
cloud_monitoring_metrics_fetch \
  --project my-project \
  --metricType bigquerybiengine.googleapis.com/reservation/used_bytes \
  --resourceType bigquery_project \
  --start $(gdate --date '1 days ago' '+%s') \
  --end $(gdate '+%s') | \
  jq -c '.[]' > out.json
```

# APIによるデータ取得
こちらで試すと値が取れます

https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list
- filter : metric.type="bigquerybiengine.googleapis.com/reservation/used_bytes"
- interval.endTime : 2022-02-03T00:00:00Z
- interval.startTime : 2022-02-02T00:00:00Z

**Comment by syou6162** [comment]
@mida-hub ご報告ありがとうございます! ご指摘の通り、型によってメトリックを取得する関数を変える必要がありました。 https://github.com/syou6162/cloud_monitoring_metrics_fetch/pull/3 で早速修正してみましたので、再度go installしなおしてもらえればと思います。

BigQueryにloadする際にもINT型にしたい場合はschemaを↓のように変更してもらえるとよさそうです(floatのままでも分析自体はほぼ問題ないかとは思います)。

- https://github.com/syou6162/cloud_monitoring_metrics_fetch/pull/3#issuecomment-1028924777

**Comment by mida-hub** [comment]
@syou6162 
対応頂きありがとうございました。無事データが取得できました。
これで一層BigQueryが捗ります m(_ _)m
